#!/usr/bin/env python3
"""
Convert Markdown presentation to PDF
"""

import os
import markdown
from weasyprint import HTML
import tempfile

def markdown_to_pdf(markdown_file, pdf_file):
    """Convert markdown file to PDF"""
    
    print(f"Converting {markdown_file} to {pdf_file}...")
    
    # Read markdown content
    with open(markdown_file, 'r', encoding='utf-8') as f:
        md_content = f.read()
    
    # Convert markdown to HTML
    html_content = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])
    
    # Create full HTML document with styling
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Polymarket Trading Strategy Presentation</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                line-height: 1.6;
            }}
            h1, h2, h3 {{
                color: #2c3e50;
                border-bottom: 2px solid #3498db;
                padding-bottom: 10px;
            }}
            table {{
                border-collapse: collapse;
                width: 100%;
                margin: 20px 0;
            }}
            th, td {{
                border: 1px solid #ddd;
                padding: 12px;
                text-align: left;
            }}
            th {{
                background-color: #f2f2f2;
                font-weight: bold;
            }}
            tr:nth-child(even) {{
                background-color: #f9f9f9;
            }}
            code {{
                background-color: #f4f4f4;
                padding: 2px 4px;
                border-radius: 3px;
                font-family: 'Courier New', monospace;
            }}
            pre {{
                background-color: #f4f4f4;
                padding: 15px;
                border-radius: 5px;
                overflow-x: auto;
            }}
            .header {{
                text-align: center;
                margin-bottom: 40px;
                padding: 20px;
                background-color: #3498db;
                color: white;
                border-radius: 5px;
            }}
            .footer {{
                text-align: center;
                margin-top: 40px;
                padding: 10px;
                font-size: 12px;
                color: #7f8c8d;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Polymarket Quantitative Trading Strategy</h1>
            <h2>Investment Presentation</h2>
            <p><strong>Date:</strong> February 10, 2026</p>
        </div>
        
        {html_content}
        
        <div class="footer">
            <p>Generated by OpenClaw AI Assistant | Confidential - For Investor Use Only</p>
            <p>Report Date: February 10, 2026</p>
        </div>
    </body>
    </html>
    """
    
    # Write HTML to temporary file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8') as f:
        f.write(full_html)
        temp_html = f.name
    
    try:
        # Convert HTML to PDF
        HTML(filename=temp_html).write_pdf(pdf_file)
        print(f"✅ PDF created successfully: {pdf_file}")
        return True
    except Exception as e:
        print(f"❌ Error creating PDF: {e}")
        return False
    finally:
        # Clean up temporary file
        if os.path.exists(temp_html):
            os.unlink(temp_html)

def main():
    input_file = "Polymarket_Investment_Presentation.md"
    output_file = "Polymarket_Investment_Presentation.pdf"
    
    if not os.path.exists(input_file):
        print(f"❌ Input file not found: {input_file}")
        return
    
    success = markdown_to_pdf(input_file, output_file)
    
    if success:
        print(f"\n📊 PDF Statistics:")
        print(f"   Input: {input_file}")
        print(f"   Output: {output_file}")
        print(f"   Size: {os.path.getsize(output_file):,} bytes")
        
        # Also create a OneDrive path suggestion
        print(f"\n💾 Save to OneDrive path:")
        print(f"   OneDrive/Trading/Polymarket_Investment_Presentation.pdf")
    else:
        print("\n❌ Failed to create PDF")

if __name__ == "__main__":
    main()